services:
  # ============================================================
  # API FASTAPI
  # ============================================================

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fastapi_api

    restart: always

    expose:
      - "8000"

    depends_on:
      - redis
      - postgres
      - minio

    env_file:
      - .env

    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000

  # ============================================================
  # WORKER RQ
  # ============================================================

  worker_inspection:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: worker_inspection

    restart: always

    depends_on:
      - redis
      - postgres
      - minio

    env_file:
      - .env

    command: >
      rq worker inspection reconditioning

  # ============================================================
  # POSTGRESQL
  # ============================================================

  postgres:
    image: postgres:16-alpine

    container_name: postgres

    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - pgdata:/var/lib/postgresql/data

  # ============================================================
  # REDIS
  # ============================================================

  redis:
    image: redis:7-alpine

    container_name: redis

    restart: always

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

  # ============================================================
  # MINIO
  # ============================================================

  minio:
    image: mmotors-minio:2025-09-07
    container_name: minio

    restart: always

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    command: server /data --console-address ":9001"

    volumes:
      - minio_data:/data

volumes:
  pgdata:

  redis_data:

  minio_data:
