"""ticket_read_statE

Revision ID: 0f8e417a2c8c
Revises: c23504cb706f
Create Date: 2026-06-30 17:53:47.222379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f8e417a2c8c'
down_revision: Union[str, Sequence[str], None] = 'c23504cb706f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_read_states', sa.Column('last_read_message_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'ticket_read_states', 'ticket_messages', ['last_read_message_id'], ['id'], ondelete='SET NULL')
    op.drop_column('ticket_read_states', 'is_read')
    op.drop_column('ticket_read_states', 'read_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_read_states', sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('ticket_read_states', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ticket_read_states', type_='foreignkey')
    op.drop_column('ticket_read_states', 'last_read_message_id')
    # ### end Alembic commands ###
