"""event_vehicle_id

Revision ID: 18239efb0ab2
Revises: 410429000c71
Create Date: 2026-08-07 16:09:07.451218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18239efb0ab2'
down_revision: Union[str, Sequence[str], None] = '410429000c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('vehicle_id', sa.String(), nullable=True))
    op.add_column('events', sa.Column('quote_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_quote_id'), 'events', ['quote_id'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_index(op.f('ix_events_vehicle_id'), 'events', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'events', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'events', 'quotes', ['quote_id'], ['id'])
    op.create_unique_constraint(None, 'payments', ['application_id'])
    op.create_index('idx_reservation_vehicle_dates', 'reservations', ['vehicle_id', 'start_date', 'end_date'], unique=False)
    op.create_unique_constraint('uq_reservation_application', 'reservations', ['application_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reservation_application', 'reservations', type_='unique')
    op.drop_index('idx_reservation_vehicle_dates', table_name='reservations')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_vehicle_id'), table_name='events')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_quote_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_column('events', 'quote_id')
    op.drop_column('events', 'vehicle_id')
    # ### end Alembic commands ###
