"""application

Revision ID: 1a4786961c43
Revises: ee800d66a824
Create Date: 2026-09-18 19:39:24.556990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4786961c43'
down_revision: Union[str, Sequence[str], None] = 'ee800d66a824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('base_price', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('optional_price', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('total_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'total_price')
    op.drop_column('applications', 'optional_price')
    op.drop_column('applications', 'base_price')
    # ### end Alembic commands ###
