"""leads_user_id

Revision ID: 23dc9bc7a659
Revises: 6ffa963919d1
Create Date: 2026-07-07 14:10:15.807912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23dc9bc7a659'
down_revision: Union[str, Sequence[str], None] = '6ffa963919d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index('ix_leads_assigned_to', 'leads', ['assigned_to'], unique=False)
    op.create_index('ix_leads_user_id', 'leads', ['user_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index('ix_leads_user_id', table_name='leads')
    op.drop_index('ix_leads_assigned_to', table_name='leads')
    op.drop_column('leads', 'user_id')
    # ### end Alembic commands ###
