"""ticket_read_state

Revision ID: 3106ffd1d279
Revises: 8c4788890771
Create Date: 2026-07-03 09:36:54.405960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3106ffd1d279'
down_revision: Union[str, Sequence[str], None] = '8c4788890771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_read_states', sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('ticket_read_states_last_read_message_id_fkey'), 'ticket_read_states', type_='foreignkey')
    op.drop_column('ticket_read_states', 'last_read_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_read_states', sa.Column('last_read_message_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('ticket_read_states_last_read_message_id_fkey'), 'ticket_read_states', 'ticket_messages', ['last_read_message_id'], ['id'], ondelete='SET NULL')
    op.drop_column('ticket_read_states', 'last_read_at')
    # ### end Alembic commands ###
