"""lead_id

Revision ID: 3185d3ef4eb8
Revises: eb4dc159ff96
Create Date: 2026-08-21 20:14:39.724478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3185d3ef4eb8'
down_revision: Union[str, Sequence[str], None] = 'eb4dc159ff96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('lead_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_events_lead_id'), 'events', ['lead_id'], unique=False)
    op.create_foreign_key(None, 'events', 'leads', ['lead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_lead_id'), table_name='events')
    op.drop_column('events', 'lead_id')
    # ### end Alembic commands ###
