"""sav_sender_role

Revision ID: 410429000c71
Revises: da91a36a9e22
Create Date: 2026-07-26 20:06:08.444841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410429000c71'
down_revision: Union[str, Sequence[str], None] = 'da91a36a9e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
op.alter_column(
    "ticket_messages",
    "sender_role",
    existing_type=sa.VARCHAR(),
    type_=sa.Enum(
        "CLIENT",
        "ADMIN",
        "SAV_AGENT",
        "SALES_AGENT",
        name="userrole"
    ),
    postgresql_using="sender_role::userrole",
    existing_nullable=False
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket_messages', 'sender_role',
               existing_type=sa.Enum('ADMIN', 'CLIENT', 'SAV_AGENT', 'SALES_AGENT', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
