"""vehicle_final_check

Revision ID: 439c7fdcfdb4
Revises: 44fb4c263e2d
Create Date: 2026-06-23 12:09:56.365364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439c7fdcfdb4'
down_revision: Union[str, Sequence[str], None] = '44fb4c263e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('final_check_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'final_check_at')
    # ### end Alembic commands ###
