"""quote

Revision ID: 5cdfa77be31c
Revises: a6dd4fedfe3f
Create Date: 2026-07-14 07:00:36.290618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdfa77be31c'
down_revision: Union[str, Sequence[str], None] = 'a6dd4fedfe3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('quotes_sales_agent_id_fkey'), 'quotes', type_='foreignkey')
    op.drop_constraint(op.f('quotes_vehicle_id_fkey'), 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'sales_agent_id')
    op.drop_column('quotes', 'vehicle_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('vehicle_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('quotes', sa.Column('sales_agent_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('quotes_vehicle_id_fkey'), 'quotes', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(op.f('quotes_sales_agent_id_fkey'), 'quotes', 'users', ['sales_agent_id'], ['id'])
    # ### end Alembic commands ###
