"""vehicle_pubslihed_at

Revision ID: 6fb70c87e030
Revises: 439c7fdcfdb4
Create Date: 2026-06-23 19:52:48.883218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb70c87e030'
down_revision: Union[str, Sequence[str], None] = '439c7fdcfdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'published_at')
    # ### end Alembic commands ###
