"""quotes

Revision ID: 88a5935bebdb
Revises: 23dc9bc7a659
Create Date: 2026-07-08 11:43:37.622503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a5935bebdb'
down_revision: Union[str, Sequence[str], None] = '23dc9bc7a659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lead_id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('sales_agent_id', sa.String(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('down_payment', sa.Float(), nullable=True),
    sa.Column('trade_in_value', sa.Float(), nullable=True),
    sa.Column('financed_amount', sa.Float(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('monthly_payment', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='quotestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['sales_agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_index(op.f('ix_quotes_lead_id'), 'quotes', ['lead_id'], unique=False)
    op.create_table('quote_trade_in',
    sa.Column('quote_id', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quote_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_trade_in')
    op.drop_index(op.f('ix_quotes_lead_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
