"""support_ticket_description

Revision ID: 8c4788890771
Revises: 0f8e417a2c8c
Create Date: 2026-07-02 20:57:39.069057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c4788890771'
down_revision: Union[str, Sequence[str], None] = '0f8e417a2c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('previous_status', sa.Enum('DRAFT', 'SUBMITTED', 'PROCESSING', 'APPROVED', 'REJECTED', 'PAID', 'COMPLETED', 'CANCELLED', name='applicationstatus'), nullable=True))
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'PROCESSING', 'APPROVED', 'REJECTED', 'PAID', 'COMPLETED', 'CANCELLED', name='applicationstatus'),
               nullable=False)
    op.add_column('support_tickets', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'description')
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'PROCESSING', 'APPROVED', 'REJECTED', 'PAID', 'COMPLETED', 'CANCELLED', name='applicationstatus'),
               nullable=True)
    op.drop_column('applications', 'previous_status')
    # ### end Alembic commands ###
