"""leads_assigned_to

Revision ID: 9dd181a9b758
Revises: 37448a3d587d
Create Date: 2026-07-06 19:21:37.108316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dd181a9b758'
down_revision: Union[str, Sequence[str], None] = '37448a3d587d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('assigned_to', sa.String(), nullable=True))
    op.alter_column('leads', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('leads', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_foreign_key(None, 'leads', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'leads', 'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.alter_column('leads', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('leads', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('leads', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('leads', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('leads', 'assigned_to')
    # ### end Alembic commands ###
