"""payment

Revision ID: a4eb63e2c5ff
Revises: 3185d3ef4eb8
Create Date: 2026-09-03 08:21:31.297237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4eb63e2c5ff'
down_revision: Union[str, Sequence[str], None] = '3185d3ef4eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.alter_column('quotes', 'trade_in_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotes', 'trade_in_value',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('payments', 'stripe_customer_id')
    # ### end Alembic commands ###
