"""application_discount

Revision ID: a6dd4fedfe3f
Revises: f2c4d8d93423
Create Date: 2026-07-11 15:27:37.053403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6dd4fedfe3f'
down_revision: Union[str, Sequence[str], None] = 'f2c4d8d93423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('discount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'discount')
    # ### end Alembic commands ###
