"""add_event_types

Revision ID: b2fb0e8a9fa0
Revises: 38890e5019de
Create Date: 2026-05-22 17:43:51.512384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2fb0e8a9fa0'
down_revision: Union[str, Sequence[str], None] = '38890e5019de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():

    # =========================
    # CREATE NEW ENUM
    # =========================
    new_enum = postgresql.ENUM(
        'PENDING',
        'CONFIRMED',
        'CANCELLED',
        'COMPLETED',
        'REJECTED',  # ✔ correct value
        name='test_drive_status_new'
    )

    new_enum.create(op.get_bind(), checkfirst=True)
    op.execute("""
        ALTER TABLE test_drives
        ALTER COLUMN status TYPE test_drive_status_new
        USING status::text::test_drive_status_new;
    """)
    op.execute("DROP TYPE testdrivestatus")
    op.execute("ALTER TYPE test_drive_status_new RENAME TO testdrivestatus")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
