"""quotes

Revision ID: bad25345a452
Revises: d223f5994182
Create Date: 2026-07-10 20:41:03.637966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad25345a452'
down_revision: Union[str, Sequence[str], None] = 'd223f5994182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

from modules.quotes.domain.enums import QuoteRefusalReason


def upgrade() -> None:

    quoterefusalreason = sa.Enum(
        QuoteRefusalReason,
    )

    quoterefusalreason.create(
        op.get_bind(),
        checkfirst=True
    )


    op.add_column(
        "quotes",
        sa.Column(
            "refusal_reason",
            quoterefusalreason,
            nullable=True
        )
    )
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('refusal_comment', sa.String(), nullable=True))
    op.add_column('quotes', sa.Column('refused_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'refused_at')
    op.drop_column('quotes', 'refusal_comment')
    quoterefusalreason = sa.Enum(
        name="quoterefusalreason"
    )

    quoterefusalreason.drop(
        op.get_bind(),
        checkfirst=True
    )
    op.drop_column('quotes', 'refusal_reason')
    # ### end Alembic commands ###
