"""ticket_read_state

Revision ID: c23504cb706f
Revises: d0629acf0bbc
Create Date: 2026-06-28 13:30:25.666415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23504cb706f'
down_revision: Union[str, Sequence[str], None] = 'd0629acf0bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_read_states',
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'user_id')
    )
    op.drop_column('support_tickets', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('ticket_read_states')
    # ### end Alembic commands ###
