"""inspection_overall_score

Revision ID: cd42254cb97e
Revises: db4fa72552fc
Create Date: 2026-07-18 15:01:40.279606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd42254cb97e'
down_revision: Union[str, Sequence[str], None] = 'db4fa72552fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('overall_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'overall_score')
    # ### end Alembic commands ###
