"""user_activation_token

Revision ID: d223f5994182
Revises: 88a5935bebdb
Create Date: 2026-07-10 10:45:55.121556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd223f5994182'
down_revision: Union[str, Sequence[str], None] = '88a5935bebdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activation_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('quote_id', sa.String(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activation_tokens_quote_id'), 'user_activation_tokens', ['quote_id'], unique=False)
    op.create_index(op.f('ix_user_activation_tokens_token_hash'), 'user_activation_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_activation_tokens_user_id'), 'user_activation_tokens', ['user_id'], unique=False)
    op.add_column('notifications', sa.Column('entity_type', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('entity_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_notifications_application_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_document_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_test_drive_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_entity_id'), 'notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_entity_type'), 'notifications', ['entity_type'], unique=False)
    op.drop_constraint(op.f('notifications_test_drive_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_document_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_application_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notifications', 'application_id')
    op.drop_column('notifications', 'test_drive_id')
    op.drop_column('notifications', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('document_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('test_drive_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('application_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('notifications_application_id_fkey'), 'notifications', 'applications', ['application_id'], ['id'])
    op.create_foreign_key(op.f('notifications_document_id_fkey'), 'notifications', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(op.f('notifications_test_drive_id_fkey'), 'notifications', 'test_drives', ['test_drive_id'], ['id'])
    op.drop_index(op.f('ix_notifications_entity_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_entity_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_test_drive_id'), 'notifications', ['test_drive_id'], unique=False)
    op.create_index(op.f('ix_notifications_document_id'), 'notifications', ['document_id'], unique=False)
    op.create_index(op.f('ix_notifications_application_id'), 'notifications', ['application_id'], unique=False)
    op.drop_column('notifications', 'entity_id')
    op.drop_column('notifications', 'entity_type')
    op.drop_index(op.f('ix_user_activation_tokens_user_id'), table_name='user_activation_tokens')
    op.drop_index(op.f('ix_user_activation_tokens_token_hash'), table_name='user_activation_tokens')
    op.drop_index(op.f('ix_user_activation_tokens_quote_id'), table_name='user_activation_tokens')
    op.drop_table('user_activation_tokens')
    # ### end Alembic commands ###
