"""warranty_plan

Revision ID: da91a36a9e22
Revises: cd42254cb97e
Create Date: 2026-07-19 20:38:20.141025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da91a36a9e22'
down_revision: Union[str, Sequence[str], None] = 'cd42254cb97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('options', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_unique_constraint('uq_option_name', 'options', ['name'])
    op.drop_column('warranty_plans', 'deductible')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warranty_plans', sa.Column('deductible', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint('uq_option_name', 'options', type_='unique')
    op.alter_column('options', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
