"""application_quote_id

Revision ID: f2c4d8d93423
Revises: bad25345a452
Create Date: 2026-07-11 10:04:57.972569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2c4d8d93423'
down_revision: Union[str, Sequence[str], None] = 'bad25345a452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('quote_id', sa.String(), nullable=True))
    op.alter_column('applications', 'birth_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_index(op.f('ix_applications_quote_id'), 'applications', ['quote_id'], unique=True)
    op.create_foreign_key(None, 'applications', 'quotes', ['quote_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_applications_quote_id'), table_name='applications')
    op.alter_column('applications', 'birth_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('applications', 'quote_id')
    # ### end Alembic commands ###
