"""quote_expires_at

Revision ID: f56c226a9918
Revises: df026b76e315
Create Date: 2026-07-15 14:29:08.059494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f56c226a9918'
down_revision: Union[str, Sequence[str], None] = 'df026b76e315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('quotes', 'expired_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('quotes', 'expires_at')
    # ### end Alembic commands ###
